import { writeFile } from 'fs/promises';
import chalk from 'chalk';
import ora from 'ora';
import path from 'path';

export async function installCommand() {
  const spinner = ora('Initializing EcoLens...').start();

  try {
    // 1. Create .env.example
    const envExample = 'CLOUDINARY_CLOUD_NAME=\n';
    await writeFile(path.join(process.cwd(), '.env.example'), envExample);
    spinner.text = 'Created .env.example';

    // 2. Create ecolens.config.json
    const config = {
      baseUrl: 'https://example.com',
      quality: 'auto',
      responsive: true,
      format: 'auto',
      crop: false
    };
    await writeFile(
      path.join(process.cwd(), 'ecolens.config.json'),
      JSON.stringify(config, null, 2)
    );
    spinner.text = 'Created ecolens.config.json';

    // 3. Create initial ecolens-report.md
    const initialReport = `# EcoLens Setup Guide

Welcome to EcoLens! Follow these steps to get started:

## 1. Cloudinary Account
- Create a free account at [Cloudinary](https://cloudinary.com/).
- Find your **Cloud Name** in the dashboard.

## 2. Configuration
- Rename \`.env.example\` to \`.env\`.
- Add your Cloudinary Cloud Name: \`CLOUDINARY_CLOUD_NAME=your_name_here\`.
- Adjust settings in \`ecolens.config.json\`, especially the \`baseUrl\` if you have relative image paths.

## 3. Run Optimization
- Run \`npx ecolens optimize\` to start scanning and rewriting image URLs.

---
*Generated by EcoLens*
`;
    await writeFile(path.join(process.cwd(), 'ecolens-report.md'), initialReport);
    spinner.succeed(chalk.green('EcoLens initialized'));

    console.log(chalk.cyan('\n✔ Created .env.example'));
    console.log(chalk.cyan('✔ Created ecolens.config.json'));
    console.log(chalk.cyan('✔ Generated ecolens-report.md'));
    
    console.log(chalk.yellow('\nNext steps:'));
    console.log('1. Rename .env.example to .env and add your CLOUDINARY_CLOUD_NAME');
    console.log('2. Set your ' + chalk.bold('baseUrl') + ' in ecolens.config.json');
    console.log('3. Run ' + chalk.bold('npx ecolens optimize'));
  } catch (error) {
    spinner.fail(chalk.red('Initialization failed'));
    throw error;
  }
}
