import { writeFile } from 'fs/promises';
import chalk from 'chalk';
import ora from 'ora';
import path from 'path';
import logSymbols from 'log-symbols';

export async function installCommand() {
  console.log(chalk.bold(`\nEcoLens CLI v1.1.0\n`));
  
  const spinner = ora('Initializing EcoLens...').start();

  try {
    // 1. Create .env.example
    const envExample = 'CLOUDINARY_CLOUD_NAME=\n';
    await writeFile(path.join(process.cwd(), '.env.example'), envExample);
    
    // 2. Create ecolens.config.json
    const config = {
      baseUrl: 'https://example.com',
      quality: 'auto',
      responsive: true,
      format: 'auto',
      crop: false
    };
    await writeFile(
      path.join(process.cwd(), 'ecolens.config.json'),
      JSON.stringify(config, null, 2)
    );

    // 3. Create initial ecolens-report.md
    const initialReport = `# EcoLens Setup Guide

Welcome to EcoLens! Follow these steps to get started:

## 1. Cloudinary Account
- Create a free account at [Cloudinary](https://cloudinary.com/).
- Find your **Cloud Name** in the dashboard.

## 2. Configuration
- Rename \`.env.example\` to \`.env\`.
- Add your Cloudinary Cloud Name: \`CLOUDINARY_CLOUD_NAME=your_name_here\`.
- Set your website URL in \`ecolens.config.json\` under \`baseUrl\`.
- Adjust other settings in \`ecolens.config.json\` if needed.

## 3. Run Optimization
- Run \`npx ecolens optimize\` to start scanning and rewriting image URLs.

---
*Generated by EcoLens*
`;
    await writeFile(path.join(process.cwd(), 'ecolens-report.md'), initialReport);

    spinner.stop();

    console.log(`${logSymbols.success} Created .env.example`);
    console.log(`${logSymbols.success} Created ecolens.config.json`);
    console.log(`${logSymbols.success} Generated ecolens-report.md`);
    
    console.log(chalk.bold('\nSetup complete.'));
    
    console.log(chalk.gray('\nNext steps:'));
    console.log(`  1. Add your ${chalk.cyan('CLOUDINARY_CLOUD_NAME')} to .env`);
    console.log(`  2. Configure your ${chalk.cyan('site URL')} in ecolens.config.json`);
    console.log(`  3. Run: ${chalk.bold('npx ecolens optimize')}\n`);

  } catch (error) {
    spinner.fail(chalk.red('Initialization failed'));
    throw error;
  }
}
