import { readFile, writeFile } from 'fs/promises';
import path from 'path';
import glob from 'fast-glob';
import chalk from 'chalk';
import ora from 'ora';
import logSymbols from 'log-symbols';
import Table from 'cli-table3';
import { config as dotenvConfig } from 'dotenv';
import { rewriteContent } from '../utils/transformer.js';

// Suppress dotenv noise by specifying path and ensuring no logs
dotenvConfig({ path: path.join(process.cwd(), '.env') });

interface OptimizationMetrics {
  totalImages: number;
  filesModified: number;
  filesScanned: number;
  estimatedOriginalSizeMB: number;
  estimatedOptimizedSizeMB: number;
}

export async function optimizeCommand() {
  console.log(chalk.bold(`\nEcoLens CLI v1.1.0\n`));

  const cloudName = process.env.CLOUDINARY_CLOUD_NAME;

  if (!cloudName) {
    console.log(`${logSymbols.error} ${chalk.red('CLOUDINARY_CLOUD_NAME missing')}`);
    console.log(chalk.gray('\nAdd it to your .env file and try again.\n'));
    process.exit(1);
  }

  // Load config
  let baseUrl: string | undefined;
  try {
    const configPath = path.join(process.cwd(), 'ecolens.config.json');
    const configContent = await readFile(configPath, 'utf-8');
    const config = JSON.parse(configContent);
    baseUrl = config.baseUrl;
  } catch (e) {
    // Config not found or invalid
  }

  const scanSpinner = ora('Scanning project...').start();

  // 1. Scan files
  const patterns = [
    '**/*.html',
    '**/*.jsx',
    '**/*.tsx',
    '**/*.js',
    '**/*.ts'
  ];
  
  const ignore = [
    'node_modules/**',
    '.next/**',
    'dist/**',
    'build/**',
    'src/**', 
    'ecolens-report.md',
    '.env',
    'package.json',
    'package-lock.json',
    'tsconfig.json'
  ];

  const files = await glob(patterns, { ignore });
  scanSpinner.stop();
  
  // We'll do a quick pre-scan to count potential images if needed, but let's stick to the flow
  console.log(`${logSymbols.success} Found ${chalk.bold(files.length)} potential files`);

  const optimizeSpinner = ora('Applying Cloudinary optimizations...').start();

  const metrics: OptimizationMetrics = {
    totalImages: 0,
    filesModified: 0,
    filesScanned: files.length,
    estimatedOriginalSizeMB: 0,
    estimatedOptimizedSizeMB: 0
  };

  const modifiedFilesList: string[] = [];
  const skippedFilesList: { file: string; reason: string }[] = [];

  // 2. Process files
  for (const file of files) {
    const filePath = path.join(process.cwd(), file);
    const content = await readFile(filePath, 'utf-8');
    
    const { newContent, count } = rewriteContent(content, cloudName, baseUrl);

    if (count > 0 && newContent !== content) {
      await writeFile(filePath, newContent, 'utf-8');
      metrics.totalImages += count;
      metrics.filesModified++;
      modifiedFilesList.push(file);
      
      // Update spinner text with current file
      optimizeSpinner.text = `Updating ${chalk.cyan(file)}...`;
    } else if (count === 0 && content.includes('src=')) {
      // It had images but they were excluded (e.g. SVG)
      if (content.includes('.svg')) {
        skippedFilesList.push({ file, reason: 'SVG already optimized or unsupported' });
      }
    }
  }

  optimizeSpinner.stop();

  // Show modified files
  modifiedFilesList.forEach(file => {
    console.log(`${logSymbols.success} Updated ${chalk.gray(file)}`);
  });

  // Show important skips
  skippedFilesList.slice(0, 3).forEach(skip => {
    console.log(`${chalk.yellow('↺')} Skipped ${chalk.gray(skip.file)} (${chalk.gray(skip.reason)})`);
  });

  if (skippedFilesList.length > 3) {
    console.log(chalk.gray(`  ... and ${skippedFilesList.length - 3} more files skipped`));
  }

  const reportSpinner = ora('Generating sustainability report...').start();

  // 3. Calculate Metrics
  const avgOriginalSizeMB = 0.5; 
  const avgSavingsRate = 0.7;
  
  metrics.estimatedOriginalSizeMB = metrics.totalImages * avgOriginalSizeMB;
  metrics.estimatedOptimizedSizeMB = metrics.estimatedOriginalSizeMB * (1 - avgSavingsRate);
  
  const totalSavingsMB = metrics.estimatedOriginalSizeMB - metrics.estimatedOptimizedSizeMB;
  const co2Reduction = totalSavingsMB * 0.2;

  // 4. Generate Report
  const report = `# EcoLens Optimization Report

## Summary
- **Images found:** ${metrics.totalImages}
- **Files scanned:** ${metrics.filesScanned}
- **Files modified:** ${metrics.filesModified}
- **Estimated savings:** ${totalSavingsMB.toFixed(2)} MB
- **Estimated CO₂ reduction:** ${co2Reduction.toFixed(2)}g/load

## Transformations Used
- \`f_auto\` (Automatic Format)
- \`q_auto\` (Automatic Quality)
- \`w_auto\` (Automatic Width)
- \`dpr_auto\` (Automatic DPR)

## Files Modified
${modifiedFilesList.map(f => `- ${f}`).join('\n')}

## Next Steps
- Verify the changes in your local environment.
- Commit the changes if everything looks good.
- Ensure your website URL is correctly set in \`ecolens.config.json\` for future runs.
- Enjoy a faster, more eco-friendly website!

---
*Generated by EcoLens on ${new Date().toLocaleString()}*
`;

  await writeFile(path.join(process.cwd(), 'ecolens-report.md'), report);
  reportSpinner.stop();
  console.log(`${logSymbols.success} Generated ${chalk.gray('ecolens-report.md')}`);

  console.log(chalk.bold('\nOptimization complete.\n'));

  // Summary Table
  console.log(chalk.cyan.bold('Optimization Summary'));
  console.log(chalk.cyan('────────────────────'));
  
  const table = new Table({
    chars: { 'top': '' , 'top-mid': '' , 'top-left': '' , 'top-right': ''
           , 'bottom': '' , 'bottom-mid': '' , 'bottom-left': '' , 'bottom-right': ''
           , 'left': '' , 'left-mid': '' , 'mid': '' , 'mid-mid': ''
           , 'right': '' , 'right-mid': '' , 'middle': '' },
    style: { 'padding-left': 0, 'padding-right': 2 }
  });

  table.push(
    ['Images Found', chalk.bold(metrics.totalImages)],
    ['Files Modified', chalk.bold(metrics.filesModified)],
    ['Estimated Savings', chalk.bold(totalSavingsMB.toFixed(2) + ' MB')],
    ['CO₂ Reduction', chalk.bold(co2Reduction.toFixed(2) + 'g/load')]
  );

  console.log(table.toString());
  console.log();
}
