import { readFile, writeFile } from 'fs/promises';
import path from 'path';
import glob from 'fast-glob';
import chalk from 'chalk';
import ora from 'ora';
import { config as dotenvConfig } from 'dotenv';
import { rewriteContent } from '../utils/transformer.js';

dotenvConfig();

interface OptimizationMetrics {
  totalImages: number;
  filesModified: number;
  filesScanned: number;
  estimatedOriginalSizeMB: number;
  estimatedOptimizedSizeMB: number;
}

export async function optimizeCommand() {
  const cloudName = process.env.CLOUDINARY_CLOUD_NAME;

  if (!cloudName) {
    console.error(chalk.red('✖ CLOUDINARY_CLOUD_NAME not found in environment.'));
    console.log('Please add it to your .env file.');
    process.exit(1);
  }

  // Load config
  let baseUrl: string | undefined;
  try {
    const configPath = path.join(process.cwd(), 'ecolens.config.json');
    const configContent = await readFile(configPath, 'utf-8');
    const config = JSON.parse(configContent);
    baseUrl = config.baseUrl;
  } catch (e) {
    // Config not found or invalid, continue without baseUrl
  }

  const spinner = ora('Scanning repository...').start();

  // 1. Scan files
  const patterns = [
    '**/*.html',
    '**/*.jsx',
    '**/*.tsx',
    '**/*.js',
    '**/*.ts'
  ];
  
  const ignore = [
    'node_modules/**',
    '.next/**',
    'dist/**',
    'build/**',
    'src/**', // Ignore source of the CLI itself
    'ecolens-report.md',
    '.env',
    'package.json',
    'package-lock.json',
    'tsconfig.json'
  ];

  const files = await glob(patterns, { ignore });
  spinner.text = `Found ${files.length} files. Applying Cloudinary transformations...`;

  const metrics: OptimizationMetrics = {
    totalImages: 0,
    filesModified: 0,
    filesScanned: files.length,
    estimatedOriginalSizeMB: 0,
    estimatedOptimizedSizeMB: 0
  };

  const modifiedFilesList: string[] = [];

  // 2. Process files
  for (const file of files) {
    const filePath = path.join(process.cwd(), file);
    const content = await readFile(filePath, 'utf-8');
    
    const { newContent, count } = rewriteContent(content, cloudName, baseUrl);

    if (count > 0 && newContent !== content) {
      await writeFile(filePath, newContent, 'utf-8');
      metrics.totalImages += count;
      metrics.filesModified++;
      modifiedFilesList.push(file);
    }
  }

  spinner.text = 'Generating optimization report...';

  // 3. Calculate Metrics
  const avgOriginalSizeMB = 0.5; 
  const avgSavingsRate = 0.7;
  
  metrics.estimatedOriginalSizeMB = metrics.totalImages * avgOriginalSizeMB;
  metrics.estimatedOptimizedSizeMB = metrics.estimatedOriginalSizeMB * (1 - avgSavingsRate);
  
  const totalSavingsMB = metrics.estimatedOriginalSizeMB - metrics.estimatedOptimizedSizeMB;
  const co2Reduction = totalSavingsMB * 0.2;

  // 4. Generate Report
  const report = `# EcoLens Optimization Report

## Summary
- **Images found:** ${metrics.totalImages}
- **Files scanned:** ${metrics.filesScanned}
- **Files modified:** ${metrics.filesModified}
- **Estimated savings:** ${totalSavingsMB.toFixed(2)} MB
- **Estimated CO₂ reduction:** ${co2Reduction.toFixed(2)}g/load

## Transformations Used
- \`f_auto\` (Automatic Format)
- \`q_auto\` (Automatic Quality)
- \`w_auto\` (Automatic Width)
- \`dpr_auto\` (Automatic DPR)

## Files Modified
${modifiedFilesList.map(f => `- ${f}`).join('\n')}

## Next Steps
- Verify the changes in your local environment.
- Commit the changes if everything looks good.
- Enjoy a faster, more eco-friendly website!

---
*Generated by EcoLens on ${new Date().toLocaleString()}*
`;

  await writeFile(path.join(process.cwd(), 'ecolens-report.md'), report);

  spinner.succeed(chalk.green('Optimization complete'));

  console.log(chalk.cyan('\n📊 Optimization Summary:'));
  console.log(`- Images Found: ${chalk.bold(metrics.totalImages)}`);
  console.log(`- Files Modified: ${chalk.bold(metrics.filesModified)}`);
  console.log(`- Estimated Savings: ${chalk.bold(totalSavingsMB.toFixed(2) + ' MB')}`);
  console.log(`- CO₂ Reduction: ${chalk.bold(co2Reduction.toFixed(2) + 'g/load')}`);
}
